name: Build and Deploy yuryshev-functionapp

on:
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: yuryshev-functionapp
  AZURE_FUNCTIONAPP_PACKAGE_PATH: ./publish
  DOTNET_CORE_VERSION: 8.0.x  

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Restore
      run : dotnet restore ./AzureFunctionsTest.sln

    - name: Build
      run: dotnet build ./AzureFunctionsTest.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./AzureFunctionsTest.sln --configuration Release --no-build --output '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.YURYSHEV_FUNCTIONAPP_034B }}
        package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"

